### ISSUE TITLE
Al guardar el comprobante no respeta el UTF-8

### ISSUE THREAD

**Issue by kyofireleo** [GrupoCorasa/cfdi-base#10]
Cuando utilizo el metodo guardar de la clase CFDv33, los acentos o Ñs no aparecen en el XML, por lo tanto el sello me sale invalido, este metodo se hereda de su abuelo (CFDCommon) y comparandolo con versiones del mx.bigdata parece ser que falta el parametro "UTF8" al metodo getBytes(), o puede que sea otra cosa, ya implemente la version 4.0.2 pero sigue con el mismo problema, me pudieran apoyar porfavor?

Postdata:

Cuando corro mi aplicacion desde NetBeans trabaja todo superbien, pero al momento de pasar los ejecutables a otra computadora pasa los que les hablo arriba.

De antemano, muchas gracias

**Comment by hortegag91** [comment]
Se acaba de subir una nueva versión en donde trae el encoding de los métodos. Confirmame y cierra el issue si quedó resuelto con esto por favor.

**Comment by kyofireleo** [comment]
Hola que tal, ya actualice la nueva version pero sigue con el mismo problema, no se si ocupe poner alguna libreria especial o asignar un parametro o que rollo.

**Comment by hortegag91** [comment]
Estas revisando bien el objeto antes de darle guardar? si estas seguro que los parámetros vienen bien antes de llamar al método Guardar?

**Comment by kyofireleo** [comment]
asi es, en el ejemplo que traigo es en el nombre del Emisor, trae una Ó, entonces no sale bien al guardar, pero si esta bien antes de.

**Comment by kyofireleo** [comment]
Te adjunto una imagen, donde muestro el nombre del Emisor antes de guardar y luego te muestro el XML en la consola
![Captura](https://user-images.githubusercontent.com/7017755/148302481-fac4de42-5c65-402f-a7c1-d886f506d581.PNG)
.

**Comment by kyofireleo** [comment]
Ya encontre el problema, al momento que se hace "baos.toString()" en el metodo guardar, no se le pone el charset "UTF-8" y es ahi donde pierde el encoding, tuve que sacar la logica del metodo para darme cuenta de eso.

Deberia de quedar como: baos.toString("UTF-8")

**Comment by hortegag91** [comment]
Listo, le habia puesto el encoding creo que a todo, menos a esa línea
Ya quedó en la 4.0.6
Te pido cierres el issue si quedó resuelto
