### ISSUE TITLE
¿Cómo compilar desde la terminal en linux?

### ISSUE THREAD

**Issue by supershadowuser** [GrupoCorasa/cfdi-base#11]
Buenas noches, disculpa nunca he usado gradle y tengo duda como compilar el proyecto desde la terminal en linux, de antemano muchas gracias por el aporte y por el apoyo.

**Comment by hortegag91** [comment]
Si lo quieres hacer manualmente, requieres instalar gradle, despues ejecutar el task "satResources" y posteirormente el task "build".
Lo más sencillo es utilizar un IDE que normalmente traen ya integrado gradle, y solo debes correr los tasks.
Para gradle hay una página oficial donde te vas a encontrar guias de como instalarlo y ejecutar tasks
https://gradle.org

**Comment by supershadowuser** [comment]
Hola de nuevo, podria indicarme por favor que IDE, versión de Gradle y Versión de Java utilizó para elaborar el proyecto? de antemano muchas gracias.

**Comment by hortegag91** [comment]
El IDE que se utilizó originalmente fue IntellijIDEA, con el jdk8 y la versión de gradle que viene integrada en el IDE.
