### ISSUE TITLE
Error CFDI40102

### ISSUE THREAD

**Issue by mperez17** [GrupoCorasa/cfdi-base#14]
Hola, 

Estoy haciendo la migración a la versión 4.0 y me arroja el error CFDI40102:

"El resultado de la digestión debe ser igual al resultado de la desencripción del sello."

"Desencriptar el contenido de este atributo usando el certificado incluido en el atributo "Certificado". Generar la cadena original del comprobante. Aplicar el algoritmo de digestión SHA-256. El resultado de la digestión debe ser igual al resultado de la desencripción del sello."

En la clase CFDv4 está la siguiente línea (26):

 protected String getDigestAlgorithm() {
        return "SHA1withRSA";
    }

No debería ser SHA256withRSA ?

**Comment by JCTOTTI10** [comment]
Hola yo tengo exactamente el mismo problema
Incumplimiento normativo.El resultado de la digestión debe ser igual al resultado de la desencripción del sello (*RSA signature did not verify*)
. Saludos

**Comment by mperez17** [comment]
> Hola yo tengo exactamente el mismo problema Incumplimiento normativo.El resultado de la digestión debe ser igual al resultado de la desencripción del sello (_RSA signature did not verify_) . Saludos

Hola, ya lo probé cambiando el algoritmo a SHA256withRSA y sí funciona, podrías verificarlo? y de ser así crear el pull request? (no se cómo)

**Comment by JCTOTTI10** [comment]
ok dejame hacer ese cambio para probarlo y ver si me sirve.

**Comment by JCTOTTI10** [comment]
@mperez17 tienes razon con ese cambio si jala...

**Comment by hortegag91** [comment]
Tienen listo algún pull request? o realizo los cambios y actualizo?

**Comment by JCTOTTI10** [comment]
@hortegag91 ya te hice el pull con el cambio para q lo puedas revisar. Saludos

**Comment by JCTOTTI10** [comment]
@hortegag91 quedara en la version 4.0.9 o vas a actualizar el compilado?

**Comment by hortegag91** [comment]
Quedó ya la nueva versión publicada el github packages
https://github.com/GrupoCorasa/cfdi-base/packages/1120118
Muchas gracias por el apoyo @JCTOTTI10 !
