### ISSUE TITLE
Nomina para CFDI 4.0

### ISSUE THREAD

**Issue by acrkorn** [GrupoCorasa/cfdi-base#18]
Hola a todos,
Me gustaría saber si ya implementaron el complemento de nómina en esta versión de la librería y si alguien la ha podido implementar exitosamente usando el nuevo estándar de cfdi 4.0
De antemano gracias por sus comentarios.
Saludos,

**Comment by hortegag91** [comment]
En teoría debería funcionar sin problemas. Estas teniendo algún problema?

**Comment by acrkorn** [comment]
De hecho no lo he implementado. Hace algún tiempo intenté usar el complemento detallista pero tenía errores y mejor opté por realizarlo de otra manera. Por eso preguntaba, para ver si alguien que haya intentado usarlo haya tenido éxito.
Vi el ejemplo en los tests, voy a intentar usarlo y si tengo algún problema regreso con ustedes.
Gracias.

PD. Excelente trabajo con el mantenimiento, la factura "normal" nunca me ha dado ningún problema.

**Comment by hortegag91** [comment]
En teoría todos los complementos se implementan exactamente de la misma manera, y el complemento nómina y pagos funcionan correctamente. El detallista debería, si pudieras dar más detalles del error que te marcó estaría ideal para poder apoyarte a resolverlos.
