### ISSUE TITLE
Namespace CartaPorte20 - xmlns:ns2

### ISSUE THREAD

**Issue by Theroberth** [GrupoCorasa/cfdi-base#20]
Buen día.

Tengo un problema con el namespace de la carta porte, anteriormente para generarlo lo hacía de esta manera:

```
cfdi = new CFDv33(comprobante, "mx.bigdata.sat.common.cartaporte.schema");
cfdi.addNamespace("http://www.sat.gob.mx/CartaPorte20", "cartaporte20");
```

Esto era en la versión 3.3, pero al actualizarse a la 4.0 el método de "addNamespace" se ve remplazado por "addSchemaLocation", dando cómo resultado el siguiente código:
```
cfdi = new CFDv40(comprobante, "mx.grupocorasa.sat.common.CartaPorte20");
cfdi.addSchemaLocation("http://www.sat.gob.mx/CartaPorte20");
```

Al verse generado el comprobante se cuenta con lo siguiente:
```
xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd http://www.sat.gob.mx/CartaPorte20" 
xmlns:cfdi="http://www.sat.gob.mx/cfd/4" 
xmlns:ns2="http://www.sat.gob.mx/CartaPorte20"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```

Una vez llenado el comprobante y verificando que todos los campos se hayan agregado correctamente, las etiquetas de carta porte se llenan con el prefijo ns2 y se regresa el siguiente error: 
CO1001 - Nombre de Complemento no declarado correctamente. ns2:CartaPorte
Ya que el xmlns de carta porte tiene el prefijo de ns2, siendo que debería ser cartaporte20.

Agradecería cualquier comentario de ayuda sobre agregar correctamente el namespace.

Saludos.

**Comment by hortegag91** [comment]
En teoría la librería ya está preparada para que NO tengas que agregas los namespace ni el schemaLocation a menos que estes agregando una addenda.
Puedes revisar en los tests como se está generando la nómina por ejemplo (sería exactamente el mismo proceso para cualquier complemento).
Comentas como te fue

**Comment by Theroberth** [comment]
La forma en la que pudimos reparar para que la etiqueta aparezca correctamente fue de la siguiente manera.

```
cfdi = new CFDv40(comprobante, "mx.grupocorasa.sat.common.CartaPorte20");
cfdi.addSchemaLocation("http://www.sat.gob.mx/CartaPorte20");
cfdi.addSchemaLocation("http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd");
cfdi.getLocalPrefixes().put("http://www.sat.gob.mx/CartaPorte20", "cartaporte20");
```

Gracias por el comentario, si vimos los ejemplos en los test, pero los corregimos cómo mencionamos anteriormente.

Saludos.
