### ISSUE TITLE
java.lang.StackOverflowError con la tarea satResources

### ISSUE THREAD

**Issue by rccardero** [GrupoCorasa/cfdi-base#21]
Saludos, ¿qué estoy haciendo mal? 
No termina de descargar todos los recursos. En este punto de la ejecución de la tarea 'satResources' se lanza el error:

....
Download http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/cadenaoriginal_TFD_1_1.xslt
Download http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd
Download http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI/tdCFDI.xsd

> Task :satResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':satResources'.
> java.lang.StackOverflowError (no error message)

**Comment by rayntriton** [comment]
intenta aumentar la memoria de la maquina de java.
Edita/crea  el archivo  "gradle.properties" y agrega:
```properties
org.gradle.jvmargs=-Xmx4608M

**Comment by hortegag91** [comment]
Funcionó aumentar la memoria? 
Otra cosa es que puedes darle primero al cleanSatResources antes del satResources
Quedamos pendientes de respuesta

**Comment by rccardero** [comment]
Hola, sí, funcionó perfectamente. Muchísimas gracias.

**Comment by hortegag91** [comment]
> ```ini
> org.gradle.jvmargs=-Xmx4608M
> ```

Quisieras hacer un pull request, o lo hago yo?
