### ISSUE TITLE
Ayuda generar complemento nómina

### ISSUE THREAD

**Issue by ihuertat** [GrupoCorasa/cfdi-base#24]
Espero que puedan apoyarme... uso la bilbioteca para generar comprobantes de nómina
Cuando lo intento, el tag que debiera ser 

 <nomina12:Nomina Version="1.2"  >

me sale como :

  <ns2:Nomina Version="1.2" >

Saben como se corrige eso? ayuda.

**Comment by hortegag91** [comment]
Podrias compartir que código estas utilizando para generar el CFDi por favor,

**Comment by ihuertat** [comment]
Este es el código pero tuve que agregar las líneas 

  ```
mx.grupocorasa.sat.cfd._33.Comprobante comprobante;
  comprobante = CFDv33Factory12.createComprobante(to, detalles);
 cfd = new CFDv33(comprobante,"mx.grupocorasa.sat.common.nomina12");
 cfd.addSchemaLocation("http://www.sat.gob.mx/nomina12");
 cfd.addSchemaLocation("http://www.sat.gob.mx/sitio_internet/cfd/nomina/nomina12.xsd");
```

Tuve que modificar el método addNamespace, a public para que me generara el tag bien...

`cfd.addNamespace("http://www.sat.gob.mx/nomina12", "nomina12");  
`
Ahora necesito integrar el namespace

`xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" `

creí que agregando la siguiente línea se podría pero no me funciona.

 ` cfd.addNamespace("http://www.sat.gob.mx/TimbreFiscalDigital","tfd"); *****    Esta línea no funciona..
`
Alguna sugerencia?

**Comment by hortegag91** [comment]
En teoría debería agregar los namespaces y schemalocation de todos los complementos de manera automática, intenta solo instanciandolo con el puro objeto de comprobante. Agregarlo manual sería únicamente cuando utilicemos addendas.
En caso de que no funcione te pido me indiques la versión de Java y de la libreria.

Prueba únicamente asi:
```
mx.grupocorasa.sat.cfd._33.Comprobante comprobante;
comprobante = CFDv33Factory12.createComprobante(to, detalles);
cfd = new CFDv33(comprobante);
```

**Comment by ihuertat** [comment]
Buenos días, intenté crear los comprobantes como mencionas pero no me funcionó, si utilizo adendas así que tuve que agregar el namespace de forma manual.

Uso Java 8, el ultimo update, la biblioteca que usaba era la 4.0.10 y con esa no había problema, ahora uso la 4.0.11 y noté esta eventualidad.

**Comment by hortegag91** [comment]
Estas compilando la librería? O la usas de github packages?

**Comment by ihuertat** [comment]
Al principio fue de github packages, pero al cambiar la versión a 4.0.11 me pasó lo que comento, por lo que la tuve que compilar para poder poner el método como público y poder agregar el namespace.
