### ISSUE TITLE
Ayuda con instancia

### ISSUE THREAD

**Issue by hugo-haro** [GrupoCorasa/cfdi-base#25]
Hola buen día, antes que nada agradecer el aporte de la librería, es buenísima.

La he usado desde 3.2, solo que ahora para versión 4.0 tengo un problema y no logro resolverlo. 

Al intentar crear una instancia de CFDv40, me tira un error ExceptionInInitializerError.

El error me da al crear la instancia asi CFDv40 cfd = new CFDv40(comp);

Salta al código.

public CFDv40(Comprobante comprobante, String... contexts) throws Exception {
        this.context = getContext(comprobante, contexts);
        this.document = copy(comprobante);
    }

y el la linea this.context = getContext(comprobante, contexts), me lanza el error.

Sabes cuál es el parámetro correcto a pasar por este constructor ?

CFDv40 cfd = new CFDv40(comp, "mx.grupocorasa.sat.common.????");

De antemano agradezco tus aportes y tu valiosa ayuda.

**Comment by hortegag91** [comment]
Tu código debería ser correcto, los contexts solamente deberían utilizarse cuando necesitemos agregar alguna addenda.
Podrías indicarme tu versión de Java, tu versión de la librería y el stacktrace o error que te lanza.

**Comment by hugo-haro** [comment]
Gracias por la pronta respuesta @hortegag91, 

Mi versión de java es la 17, de la librería es la 4.0.11. El stacktrace no dice mucho, pero igual te paso algunas pantallas.

<img width="1316" alt="Captura de Pantalla 2022-05-26 a la(s) 18 51 26" src="https://user-images.githubusercontent.com/5288221/170602520-95690130-18c4-4dba-9db5-ef6f58f2de27.png">

<img width="1317" alt="Captura de Pantalla 2022-05-26 a la(s) 18 51 10" src="https://user-images.githubusercontent.com/5288221/170602509-ccc831fa-30fe-4b00-8a85-b51b703ae6f9.png">

<img width="1307" alt="Captura de Pantalla 2022-05-26 a la(s) 18 49 24" src="https://user-images.githubusercontent.com/5288221/170602501-5bfe11a8-74cf-43d5-aa81-e612560d3879.png">

<img width="1032" alt="Captura de Pantalla 2022-05-26 a la(s) 18 50 44" src="https://user-images.githubusercontent.com/5288221/170602505-0b808796-726e-4515-967f-78581146ce14.png">

**Comment by hugo-haro** [comment]
@hortegag91 cambie la versión de java a 8 y ya no me dio problema. Continuo con los cambios y te cuento.

Muchas gracias.

**Comment by hortegag91** [comment]
Enterado, cierro el issue entonces :+1:
