### ISSUE TITLE
INE y DONAT

### ISSUE THREAD

**Issue by aquaerny** [GrupoCorasa/cfdi-base#26]
Hola espero que esten bien.

Me llego una factura que en el complemento están llamando ine y donat, pero no se usan. Ni se llaman en los xsi:schemaLocation. Si cargo la factura marca error "String index out of range: -1".

Lo que quiero saber si este es un error del proveedor para pedirle que lo modifique o es un problema de la librería?

`<cfdi:Comprobante
	xmlns:cfdi="http://www.sat.gob.mx/cfd/4"
	xmlns:cartaporte20="http://www.sat.gob.mx/CartaPorte20"
	xmlns:cce11="http://www.sat.gob.mx/ComercioExterior11"
	xmlns:donat="http://www.sat.gob.mx/donat"
	xmlns:ine="http://www.sat.gob.mx/ine"`

`
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960) ~[?:1.8.0_212]
	at mx.grupocorasa.sat.common.CfdCommon.getFileContext(CfdCommon.java:325) ~[cfdi-base-4.0.11.jar:?]
	at mx.grupocorasa.sat.common.CfdCommon.load(CfdCommon.java:53) ~[cfdi-base-4.0.11.jar:?]
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.<init>(CFDv40.java:71) ~[cfdi-base-4.0.11.jar:?]`

Así lo uso:

`CFDv40 cfd4 = new CFDv40(new ByteArrayInputStream(xml.getBytes()));`

Saludos, me a ayudado mucho la librería :)

**Comment by hortegag91** [comment]
En teoría no es un error que invalida la factura ni mucho menos.
Supongo que al estar declaradas, la librería intenta instanciar el objeto del complemento, y al no encontrarlo en la lista de complementos marca el error.
Una opción sería que retiraras los namespaces ya que estos NO estan incluidos en la cadena y no debería verse afectada la cadena original, por lo que aún modificandolo, seguiría teniendo validez fiscal (Sólamente retirandole los namespaces). 
Si quieres hazme llegar el XML y puedo hacer pruebas con el archivo directamente y solucionar desde la libreria el problema.

**Comment by aquaerny** [comment]
Hola si hice lo que me dijiste ayer y por eso identifique eran el ine y donat.
Claro que si te paso el xml
[FF0000000290.xml.zip](https://github.com/GrupoCorasa/cfdi-base/files/8961122/FF0000000290.xml.zip)

Gracias por la respuesta

**Comment by hortegag91** [comment]
Efectivamente el problema es que al tener declarado el namespace, está intentando verificar la versión del complemento para instanciarlo. Pero nunca la encuentra porque en realidad no tiene el complemento.
![image](https://user-images.githubusercontent.com/14035835/175134615-7615eba3-a3d8-42d2-ae1e-d72b5b1ac355.png)
Voy a intentar agregar una nueva versión, y te notifico cuando pase la prueba con ese archivo que compartiste.

**Comment by aquaerny** [comment]
Excelente muchas gracias estare pendiente :)

**Comment by hortegag91** [comment]
Acabo de subir una nueva versión, en donde hice pruebas directamente con tu archivo.
A demás del problema que ya mencioné, tambien tenia el problema que el XML venía con codificación "UTF-8 with BOM", por lo que marcaba error. Buscando en el SAT no encontré ninguna especificación más haya del UTF8, por lo que incorporé una rutina que quitara el BOM y lo manejara con la codificación de siempre.
Te encargo que si no resulta, reabras este mismo issue

**Comment by aquaerny** [comment]
muchas gracias, si ya tenía una rutina para quitar el bom, es muy común que hagan esto :( en la empresa hasta les enseñe hace muchos años como quitarlo con el notepad++

De nuevo muchas gracias :)

**Comment by hortegag91** [comment]
En teoría ya no requieren hace eso, la librería debería quitarselo al momento de leerlo :+1:
