### ISSUE TITLE
Ayuda con crear un ComplementoConcepto para Instituciones Educativas

### ISSUE THREAD

**Issue by JJAMBurgos** [GrupoCorasa/cfdi-base#28]
Estay Tratando de crear un complemento de concepto para instituciones educativas, segun mi teoria es asi:

        mx.grupocorasa.sat.cfd._40.ObjectFactory cfdi_of = new mx.grupocorasa.sat.cfd._40.ObjectFactory();
	    Conceptos conceptos = cfdi_of.createComprobanteConceptos();
	    List<Concepto> listaConceptos = conceptos.getConcepto(); 
	    // Concepto
	    Concepto conce =   cfdi_of.createComprobanteConceptosConcepto();
	    conce.setClaveUnidad(CClaveUnidad.fromValue("E48"));
		conce.setClaveProdServ("86121600");
		conce.setNoIdentificacion("86121600");
		conce.setCantidad(new BigDecimal("1"));
		conce.setDescripcion("Colegiatura");
		conce.setValorUnitario(Importe);
		conce.setImporte(Importe);
		conce.setObjetoImp(CObjetoImp.fromValue("02"));
		
		 //Complemento Concepto
		
		mx.grupocorasa.sat.common.iedu10.ObjectFactory ie_of = new mx.grupocorasa.sat.common.iedu10.ObjectFactory();
		InstEducativas educacion = ie_of.createInstEducativas();
    	educacion.setVersion("1.0");
    	educacion.setAutRVOE("15PCT07784");
    	educacion.setCURP("DAVK011214MNELVRA9");
    	educacion.setNombreAlumno("DANIELA PLATA VIVAS");
    	educacion.setNivelEducativo("Bachillerato o su equivalente");
    	educacion.setRfcPago("GIMA820726BZ3");
    	ComplementoConcepto compleConcepto =  cfdi_of.createComprobanteConceptosConceptoComplementoConcepto();
    	compleConcepto.getAny().add(educacion);
    	
    	conce.setComplementoConcepto(compleConcepto);
		
		// Impuestos Concepto
		Concepto.Impuestos c1I = cfdi_ofcreateComprobanteConceptosConceptoImpuestos();
		mx.grupocorasa.sat.cfd._40.Comprobante.Conceptos.Concepto.Impuestos.Traslados trans =  cfdi_of.createComprobanteConceptosConceptoImpuestosTraslados();
		List<mx.grupocorasa.sat.cfd._40.Comprobante.Conceptos.Concepto.Impuestos.Traslados.Traslado> listaTraslados =  trans.getTraslado();
		Concepto.Impuestos.Traslados.Traslado tr1 = scfdi_of.createComprobanteConceptosConceptoImpuestosTrasladosTraslado();
		tr1.setBase(Importe);
	    tr1.setImpuesto(CImpuesto.fromValue("002"));
	    tr1.setTipoFactor(CTipoFactor.TASA);
	    tr1.setTasaOCuota(new BigDecimal("0.000000"));
	    tr1.setImporte(new BigDecimal("0.00"));
	    listaTraslados.add(tr1);
	    c1I.setTraslados(trans);
	    conce.setImpuestos(c1I);
	    listaConceptos.add(conce);

	    // Adicion a Doc principal
	    comp.setConceptos(conceptos);

pero me genera este error:

javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.SAXException2: class mx.grupocorasa.sat.common.iedu10.InstEducativas ni ninguna de sus superclases se conocen en este contexto.
javax.xml.bind.JAXBException: class mx.grupocorasa.sat.common.iedu10.InstEducativas ni ninguna de sus superclases se conocen en este contexto.]

Gracias por su ayuda

**Comment by hortegag91** [comment]
En teoría debería funcionar. Revisé y me di cuenta que se estaban importando los esquemas únicamente del nodo complemento del comprobante, pero este nodo complemento está dentro del concepto por lo que nunca se importaba.
Acabo de subir una nueva versión donde en teoría ya funciona. Hice pruebas muy básicas pero te agradeceré si pudieras abrir un nuevo issue si te llegase a dar errores nuevos.

**Comment by JJAMBurgos** [comment]
Gracias todo salio perfecto
