### ISSUE TITLE
Detalle al leer un xml con la libreria

### ISSUE THREAD

**Issue by JJAMBurgos** [GrupoCorasa/cfdi-base#29]
Cuando se lee un archivo xml con la libreria no lo lee con la codificacion UTF-8 y por lo tanto todos los caracteres especiales salen raros.

Encontre el problema segun yo esta en:

mx.grupocorasa.sat.common.CfdCommon

en el metodo load

hay que cambiar la linea:
**try (Reader reader = new InputStreamReader(copies.get(1))) {**

por:
**try (Reader reader = new InputStreamReader(copies.get(1),StandardCharsets.UTF_8)) {**

y ya se lee bien la información.

Gracias y Saludos

**Comment by hortegag91** [comment]
Ya debería funcionar correctamente, supongo que el problema te lo daba en Windows ya que la codificación por default es diferente. Si el problema persiste, reabre el issue por favor.
