### ISSUE TITLE
Carta Porte 2.0 javax.xml.bind.JAXBException

### ISSUE THREAD

**Issue by markh42** [GrupoCorasa/cfdi-base#3]
Hola!, de antemano gracias por el aporte del proyecto, migre la versión anterior a esta  contemplando Carta Porte 2.0, todo me funciona correctamente desde intellij en desarrollo, sin embargo al momento de empaquetar el código por algún motivo obtengo el siguiente error al solamente al usar cartaPorte 2.0

javax.xml.bind.JAXBException: class mx.grupocorasa.sat.common.CartaPorte20.CartaPorte nor any of its super class is known to this context.]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:326)
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:251)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(Unknown Source)
	at mx.grupocorasa.sat.cfdi.CFDv33.copy(CFDv33.java:184)
	at mx.grupocorasa.sat.cfdi.CFDv33.<init>(CFDv33.java:80)

Después de descartar algún problema con mi código abro este issue para solicitar el apoyo si es algo relacionado a esta nueva versión. 

Saludos

**Comment by hortegag91** [comment]
Podrías indicarme que versión estas utilizando y compartir como estas instanciando los objetos?
Acabo de hacer una prueba (únicamente agregandole la versión) y se generó el XML sin problemas.
Este es el código que usé de prueba:

```
        CartaPorte cartaPorte = new ObjectFactory().createCartaPorte();
        cartaPorte.setVersion("2.0");
        Comprobante comprobante = ExampleCFDv33Factory.getInstance().createComplementoPago();
        Comprobante.Complemento complemento = ExampleCFDv33Factory.getInstance().createComplemento();
        complemento.getAny().add(cartaPorte);
        comprobante.getComplemento().add(complemento);
        CFDv33 cfd = new CFDv33(comprobante);
        cfd.guardar(System.out, true);
```

Y este fue el resultado:
```
<?xml version="1.0" encoding="UTF-8"?><cfdi:Comprobante Version="3.3" Serie="PPP" Folio="34152" Fecha="2021-03-11T14:54:56" SubTotal="0" Moneda="XXX" Total="0" TipoDeComprobante="P" LugarExpedicion="83000" Confirmacion="ECVH1" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/CartaPorte20 http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd" xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:CartaPorte20="http://www.sat.gob.mx/CartaPorte20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <cfdi:CfdiRelacionados TipoRelacion="06">
        <cfdi:CfdiRelacionado UUID="248C01A6-A08C-4821-BFAF-F1D04C0A0DC5"/>
        <cfdi:CfdiRelacionado UUID="4A3CC52B-4F7A-4FAF-9375-9905D535CB07"/>
    </cfdi:CfdiRelacionados>
    <cfdi:Emisor Rfc="PPL961114GZ1" Nombre="PHARMA PLUS SA DE CV" RegimenFiscal="606"/>
    <cfdi:Receptor Rfc="OEGH910609BZ6" Nombre="Heriberto Ortega Gonzalez" UsoCFDI="P01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <CartaPorte20:CartaPorte Version="2.0"/>
    </cfdi:Complemento>
</cfdi:Comprobante>Disconnected from the target VM, address: 'localhost:35507', transport: 'socket'
BUILD SUCCESSFUL in 46s
```

**Comment by markh42** [comment]
La implementación la tengo igual como la mencionas, de hecho solo cambie los paquetes y ajuste el código del proyecto anterior, he estado probando para verificar que mi código sea el origen del problema, puedo ver dos cosas, si lo hago a través de Intellij funciona perfectamente, pero cuando creo el jar y ejecuto lo mismo, me falla cuando hay un complemento no importa si es carta porte 1,2 o Pago etc. 
Podrías probar este código para convertir el objeto a string para ayudarme a verificar si el error es un inconveniente de mi parte ?

`Pagos c_pago = ExampleComplementoPagoFactory.getInstance().createComplementoPago();`
` Comprobante comprobante = ExampleCFDv33Factory.getInstance().createComplementoPago();` 
`Comprobante.Complemento complemento = ExampleCFDv33Factory.getInstance().createComplemento();` `complemento.getAny().add(c_pago); comprobante.getComplemento().add(complemento);`
 `CFDv33 cfd = new CFDv33(comprobante);`

`JAXBContext jaxbContext = JAXBContext.newInstance(Comprobante.class); `
`Marshaller jaxbMarshaller = jaxbContext.createMarshaller(); `
`StringWriter sw1 = new StringWriter(); `
`jaxbMarshaller.marshal(comprobante, sw1); `
`System.out.println(sw1); `

Con la finalidad de verificar que JAXB puede representar el complemento?

**Comment by markh42** [comment]
Retomo el issue para notificar por si alguien tiene la misma tecnologia y presenta el mismo error, dependiendo del IDE a usar, en mi caso Intellij IDEA cuando compila y ejecuta el código pone todas las dependencias directo en el classpath por lo cual funciona sin problema, cuando se realiza el **_goal de maven "package" con el plugin spring-boot-maven-plugin y spring boot_**  una vez compilado al momento de ejecutar el jar no encuentra las clases que son dependencia de la dependencia dentro classpath y origina el problema de jackson al no cargar todas las clases y no encontrar un match sobre el contexto a usar, el cual pude solucionar de la siguiente forma. 

```
      <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <executions>
              <execution>
                  <goals>
                      <goal>repackage</goal>
                  </goals>
              </execution>
          </executions>
          <configuration>
              <includeSystemScope>true</includeSystemScope>
              <requiresUnpack>
                  <dependency>
                      <groupId>mx.grupocorasa.cfdibase</groupId>
                      <artifactId>cfdi-base</artifactId>
                  </dependency>
              </requiresUnpack>

....

```

Gracias por el apoyo, Saludos
