### ISSUE TITLE
Carta Porte 3.0

### ISSUE THREAD

**Issue by EduardoSempere** [GrupoCorasa/cfdi-base#32]
Hola espero estén muy bien, antes que nada muchas gracias por la librería creo que es muy buena, y quiero preguntar si están pensando en incluir la versión 3.0 de carta porte???
Muchas Gracias

**Comment by hortegag91** [comment]
Seguro, de hecho desde versiones anteriores, se agregó un proceso que una vez liberada la documentación téccnica, por medio de un task, actualiza toda la librería. Espero durante esta semana tener tiempo de correr el task y se haga la actualización. Cuenta con la versión 3.0 del carta porte muy pronto-.

**Comment by EduardoSempere** [comment]
Son muy buenas noticias , por si te ayuda en algo esta es la pagina del SAT http://omawww.sat.gob.mx/tramitesyservicios/Paginas/complemento_carta_porte.htm , y por otro lado tienes un manual de como poder compilarlo de forma local estado probando con gradle , pero me marca un error cuando esta descargando los xsd , Execution failed for task ':satResources'.
> java.lang.StackOverflowError (no error message) , tienes algun README , donde este como compilarlo y ese proceso?

**Comment by hortegag91** [comment]
Por alguna razón marca ese error cuando intentas correr ese task sin haberlo limpiado previamente.
Intenta primero dandole al task :cleanSatResources, despues el task :clean, y luego ya el :satResources
Por otro lado, estoy revisando que NO se descargará automáticamente hasta que agreguen el complemento al archivo xslt de la versión 4.0

![image](https://github.com/GrupoCorasa/cfdi-base/assets/14035835/58777ce0-33dd-40a4-a95e-d32c8c07738b)

**Comment by EduardoSempere** [comment]
Muchas gracias, puede descargar los archivos pero continuo con un erre de path, estoy tratando de resolverlo, a ver si puedo ayudar un poco para agregar el complemento de carta porte.

**Comment by hortegag91** [comment]
Con un error del Path? Si pudieras abrir un Issue específicamente con ese error porfa. Este issue fue para los planes de liberar la versión 3.0 de Carta Porte y quedó resuelto. Para que si alguien tiene el mismo error de Path que comentas, pueda apoyarse del mismo hilo.

**Comment by EduardoSempere** [comment]
Hola, pude hacerlo funcionar , y le agregue un parche , fue lo que se me ocurrio para agregar por lo mientras  carta porte 
![image](https://github.com/GrupoCorasa/cfdi-base/assets/55951641/1896b52b-7388-44ff-997c-775cd6b4d7cf)
