### ISSUE TITLE
Codigo ejemplo CFDI 4.0

### ISSUE THREAD

**Issue by cherlux82** [GrupoCorasa/cfdi-base#4]
Hola. Tendran codigo ejemplo de como se leeran las facturas 4.0

**Comment by hortegag91** [comment]
De momento aún no soporta la versión 4.0, pero pronto estará lista. Sería de manera similar a las otras versiónes, solo que con el nuevo número de la versión.
Tan pronto como esté lista, subiré un ejemplo.

**Comment by hortegag91** [comment]
Está lista la versión 4.0, se genera igual que las otras versiones, solo utilizando el objeto v40.
Saludos
