### ISSUE TITLE
Crear CFDv33

### ISSUE THREAD

**Issue by juanfra0064** [GrupoCorasa/cfdi-base#6]
En la version anterior para crear un CFDv33 para una factura usaba este constructor
 new CFDv33(comprobante);
y para crear un REP este otro
new CFDv33(comprobante, "mx.bigdata.sat.common.pagos.schema"); se le pasaba el contexto

En esta version solo existe este constructor
new CFDv33(comprobante)

Para crear un REP se utiliza este?

**Comment by hortegag91** [comment]
En teoría la librería está preparada para hacer esto de manera automática en el método
```java
private void defineContexts(List<String> contexts, ClassPath.ClassInfo info)
```
Al definir el objeto como mencionar, debería crearlo correctamente, en caso de que no, reabres el issue
