### ISSUE TITLE
Prefijo y namespace con error: CartaPorte20 - http://www.sat.gob.mx/CartaPorte20

### ISSUE THREAD

**Issue by hix-angelica-rojas** [GrupoCorasa/cfdi-base#9]
Hola, buena tarde
He estado haciendo pruebas creando xml y sellándolos con éxito.
Pero al momento de mandar a timbrar, mi pac me manda el siguiente error (el xml lo mando con base64): 

![Screenshot_2021-12-30_17-03-18](https://user-images.githubusercontent.com/36086362/147793322-4dcfbdf1-1599-428b-bf4f-e2a4d9516f1b.png)

Bueno, lo que hice fue reemplazar la siguiente línea de mi xml: 
xmlns:CartaPorte20="http://www.sat.gob.mx/CartaPorte20" 
por xmlns:cartaporte20="http://www.sat.gob.mx/CartaPorte20" y a su vez en todos los nodos que contienen <CartaPorte20:CartaPorte.... />
por <cartaporte20:CartaPorte... /> y así ya pude mandar a timbrar correctamente :+1: 

No sé si todos los pacs validen ese dato de haber escrito correctamente el prefijo de carta porte, pero viendo el documento .xslt de carta porte, estos datos están con minúscula jeje (supongo que acaban de actualizar los documentos)
http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xslt

**Comment by hortegag91** [comment]
Efectivamente estas en lo correcto, haré los cambios correspondientes para en próximas versiones que no sea necesario estar reemplazando el namespace. Gracias por reportarlo

**Comment by hix-angelica-rojas** [comment]
Encontré algo extraño al momento de sellar el comprobante, me está generando el campo de schemaLocation de esta forma:
xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/CartaPorte20 http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte20/CartaPorte20.xsd http://www.sat.gob.mx/CartaPorte http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte.xsd"

cuando la forma correcta debe ser la siguiente:
xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/CartaPorte20 http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd"

lo que veo es que se está agregando 2 veces el schema de carta porte :/

**Comment by hortegag91** [comment]
Que extraño, ya estuve haciendo pruebas y pude corregir lo del namespace, pero a mi no me pasó la duplicidad del schemaLocation, podrías compartir como estas generando el XML?
En unos momentos subo la nueva versión donde genera correctamente los namespaces.

**Comment by hortegag91** [comment]
Lista la nueva versión, si el problema persiste reabres el issue por favor.
https://github.com/GrupoCorasa/cfdi-base/packages/1120118

**Comment by hix-angelica-rojas** [comment]
Ya pude ver lo que pasaba, al momento de darle guardar lo estaba usando con ByteArrayOutputStream:
CFDv33 cfd = new CFDv33(c);
ByteArrayOutputStream bos = new ByteArrayOutputStream();
cfd.guardar(bos, true);
y así es como me genera duplicidad de schemaLocation.

Pero si ya lo mando así:
CFDv33 cfd = new CFDv33(c);
cfd.guardar(System.out, true);

ya no me ocurre ese issue :+1: 
y bueno, aquí confirmando que lo de namespace funciona bien :D 
gracias!
